baseURL = "https://narumiruna.github.io/bin/"
languageCode = "zh-tw"
title = "Bin"
defaultContentLanguage = "zh-tw"
enableRobotsTXT = true

[params]
description = "筆記與字幕整理網站"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
